spring.application.name=web-security26
spring.security.user.name=admin
spring.security.user.password=admin

server.port=8080

spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=web-security-26